import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"

const fontHeading = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-heading"
})

const fontBody = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-body"
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${
          (fontHeading.variable, fontBody.variable)
        } antialiased flex min-h-screen w-full flex-col items-center justify-center bg-background`}
      >
        {children}
      </body>
    </html>
  )
}
