import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"

export const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} antialiased flex min-h-screen w-full flex-col items-center justify-center bg-background`}
      >
        {children}
      </body>
    </html>
  )
}
